<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'f0d00976a2d23950039e2e828cde3af1',
  'DATABASE_URL' => 'mysql://335775_test:marsaudolivier@mysql-olivier79700.alwaysdata.net:3306/olivier79700_sandrine?serverVersion=8.0.32&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
);
